# New ports collection makefile for:	xf86-video-dummy
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-dummy/Makefile,v 1.12 2011/11/09 15:25:57 miwi Exp $
#

PORTNAME=	xf86-video-dummy
PORTVERSION=	0.3.5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org dummy display driver

XORG_CAT=	driver
USE_XORG=	videoproto xf86dgaproto

.include <bsd.port.mk>
