# New ports collection makefile for:	xf86-video-vmware
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-vmware/Makefile,v 1.7 2009/05/07 19:42:40 rnoland Exp $
#

PORTNAME=	xf86-video-vmware
PORTVERSION=	10.16.9
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org vmware display driver

XORG_CAT=	driver
USE_XORG=	xextproto xineramaproto videoproto

MAN4=		vmware.4x

.include <bsd.port.mk>
