# New ports collection makefile for:	xf86-video-vmware
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-vmware/Makefile,v 1.12 2011/01/06 22:11:56 mi Exp $
#

PORTNAME=	xf86-video-vmware
PORTVERSION=	11.0.3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org vmware display driver

XORG_CAT=	driver
USE_XORG=	xextproto xineramaproto videoproto

MAN4=		vmware.4x

.include <bsd.port.mk>
