# New ports collection makefile for:	scrnsaverproto
# Date Created:				21 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/scrnsaverproto/Makefile,v 1.1 2007/05/19 20:27:18 flz Exp $
#

PORTNAME=	scrnsaverproto
PORTVERSION=	1.2.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	ScrnSaver extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
