# New ports collection makefile for:	scrnsaverproto
# Date Created:				21 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/scrnsaverproto/Makefile,v 1.2 2010/05/01 11:40:16 miwi Exp $
#

PORTNAME=	scrnsaverproto
PORTVERSION=	1.2.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	ScrnSaver extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
