# $FreeBSD$

PORTNAME=	xf86-video-chips
PORTVERSION=	1.2.5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org chips display driver

XORG_CAT=	driver
USE_XORG=	xorg-macros
MAN4=		chips.4x

.include <bsd.port.mk>
