# New ports collection makefile for:	xf86-video-chips
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-chips/Makefile,v 1.6 2009/05/07 19:42:35 rnoland Exp $
#

PORTNAME=	xf86-video-chips
PORTVERSION=	1.2.2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org chips display driver

XORG_CAT=	driver
USE_XORG=	videoproto xextproto
MAN4=		chips.4x

.include <bsd.port.mk>
