# New ports collection makefile for:	xwd
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xwd/Makefile,v 1.2 2009/01/23 16:28:25 flz Exp $
#

PORTNAME=	xwd
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Dump an image of an X window

XORG_CAT=	app
USE_XORG=	xmuu x11

PLIST_FILES=	bin/xwd

MAN1=		xwd.1

.include <bsd.port.mk>
