# New ports collection makefile for:	xedit
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xedit/Makefile,v 1.2 2009/01/23 16:28:18 flz Exp $
#

PORTNAME=	xedit
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Simple text editor for X

XORG_CAT=	app
USE_XORG=	xt xaw7

MAN1=		xedit.1

.include <bsd.port.mk>
