# New ports collection makefile for:	xhost
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xhost/Makefile,v 1.3 2010/05/01 11:40:22 miwi Exp $
#

PORTNAME=	xhost
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Server access control program for X

XORG_CAT=	app
USE_XORG=	x11 xmuu xau

PLIST_FILES=	bin/xhost

MAN1=		xhost.1

.include <bsd.port.mk>
