# New ports collection makefile for:	xrandr
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xrandr/Makefile,v 1.4 2009/04/04 04:03:55 rnoland Exp $
#

PORTNAME=	xrandr
PORTVERSION=	1.3.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Primitive command line interface to the RandR extension

XORG_CAT=	app
USE_XORG=	xrandr xrender x11

PLIST_FILES=	bin/xrandr \
		bin/xkeystone

MAN1=		xrandr.1

.include <bsd.port.mk>
