# New ports collection makefile for:	xcmsdb
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xcmsdb/Makefile,v 1.2 2010/05/01 11:40:20 miwi Exp $
#

PORTNAME=	xcmsdb
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Device Color Characterization utility for X

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xcmsdb

MAN1=		xcmsdb.1

.include <bsd.port.mk>
