# New ports collection makefile for:	xcalc
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xcalc/Makefile,v 1.4 2010/05/01 11:40:19 miwi Exp $
#

PORTNAME=	xcalc
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Scientific calculator for X

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xcalc.1

.include <bsd.port.mk>
