# New ports collection makefile for:	kbproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/kbproto/Makefile,v 1.1 2007/05/19 20:26:42 flz Exp $
#

PORTNAME=	kbproto
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	KB extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
