# New ports collection makefile for:	xf86-video-sunffb
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-sunffb/Makefile,v 1.8 2010/02/07 15:25:32 rnoland Exp $
#

PORTNAME=	xf86-video-sunffb
PORTVERSION=	1.2.0
PORTREVISION=	5
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org sunffb display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto xextproto glproto
MAN4=		sunffb.4x

.include <bsd.port.mk>
