# New ports collection makefile for:	xvinfo
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xvinfo/Makefile,v 1.2 2007/09/13 19:45:07 flz Exp $
#

PORTNAME=	xvinfo
PORTVERSION=	1.1.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Print out X-Video extension adaptor information

XORG_CAT=	app
USE_XORG=	xv x11

PLIST_FILES=	bin/xvinfo

MAN1=		xvinfo.1

.include <bsd.port.mk>
