# New ports collection makefile for:    font-bh-lucidatypewriter-100dpi
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-bh-lucidatypewriter-100dpi/Makefile,v 1.1 2007/05/19 20:29:12 flz Exp $
#

PORTNAME=	font-bh-lucidatypewriter-100dpi
PORTVERSION=	1.0.0
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Bigelow Holmes Lucida TypeWriter 100dpi font

XORG_CAT=	font
USE_XORG=	fontutil

.include <bsd.port.mk>
