# $FreeBSD: head/x11/pixman/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	pixman
PORTVERSION=	0.32.4
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Low-level pixel manipulation library

USES=		perl5
USE_PERL5=	build
XORG_CAT=	lib
CONFIGURE_ARGS=	--disable-gtk
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
