# $FreeBSD: head/x11/pixman/Makefile 351936 2014-04-23 13:25:16Z tijl $

PORTNAME=	pixman
PORTVERSION=	0.32.4
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Low-level pixel manipulation library

USES=		perl5
USE_PERL5=	build
XORG_CAT=	lib
CONFIGURE_ARGS=	--disable-gtk
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
