# New ports collection makefile for:	xtrap
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xtrap/Makefile,v 1.1 2007/05/19 20:28:19 flz Exp $
#

PORTNAME=	xtrap
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XTrap sample clients for X

XORG_CAT=	app
USE_XORG=	xtrap

MAN1=		xtrap.1 \
		xtrapchar.1 \
		xtrapin.1 \
		xtrapinfo.1 \
		xtrapout.1 \
		xtrapproto.1 \
		xtrapreset.1 \
		xtrapstats.1

.include <bsd.port.mk>
