# New ports collection makefile for:   libxkbfile
# Date Created:			7 May 2004
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/libxkbfile/Makefile,v 1.8 2010/05/01 11:40:14 miwi Exp $
#

PORTNAME=	libxkbfile
PORTVERSION=	1.0.6
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XKB file library

XORG_CAT=	lib
USE_XORG=	x11 kbproto:both

.include <bsd.port.mk>
