# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libxkbfile/Makefile 351936 2014-04-23 13:25:16Z tijl $

PORTNAME=	libxkbfile
PORTVERSION=	1.0.8
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XKB file library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 kbproto:both

.include <bsd.port.mk>
