# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libxkbfile
PORTVERSION=	1.0.8
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XKB file library

LICENSE=	MIT

XORG_CAT=	lib
NO_STAGE=	yes
USE_XORG=	x11 kbproto:both

.include <bsd.port.mk>
