# Created by: Florent Thoumie <flz@FreeBSD.org>
# $FreeBSD$

PORTNAME=	xf86-video-savage
PORTVERSION=	2.3.6
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org savage display driver

USE_GL=		gl

WITH_FBSD10_FIX=yes
XORG_CAT=	driver
USE_XORG=	xf86driproto glproto
MAN4=		savage.4x

.include <bsd.port.mk>
