# New ports collection makefile for:   libXmu
# Date Created:			25 Jan, 2003
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/libXmu/Makefile,v 1.20 2010/05/01 11:41:06 miwi Exp $
#

PORTNAME=	libXmu
PORTVERSION=	1.1.0
PORTEPOCH=	1
CATEGORIES=	x11-toolkits

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Miscellaneous Utilities libraries

XORG_CAT=	lib
USE_XORG=	xproto:both x11 xt xext

.include <bsd.port.mk>
