# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11-toolkits/libXmu/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	libXmu
PORTVERSION=	1.1.2
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	x11-toolkits

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Miscellaneous Utilities libraries

XORG_CAT=	lib
USE_XORG=	xproto:both x11 xt xext

.include <bsd.port.mk>
