# New ports collection makefile for:	xf86-input-magictouch
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-magictouch/Makefile,v 1.10 2010/12/04 07:34:09 ade Exp $
#

PORTNAME=	xf86-input-magictouch
PORTVERSION=	1.0.0.5
PORTREVISION=	6
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org magictouch input driver

IGNORE=		needs xf86_ansic.h which doesn't exist with recent xserver

XORG_CAT=	driver
MAN4=		magictouch.4x
USE_AUTOTOOLS=	libtool

.include <bsd.port.mk>
