# New ports collection makefile for:	viewres
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/viewres/Makefile,v 1.2 2009/01/23 16:28:15 flz Exp $
#

PORTNAME=	viewres
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Graphical class browser for Xt

XORG_CAT=	app
USE_XORG=	xt xaw

PLIST_FILES=	bin/${PORTNAME}

MAN1=		viewres.1

.include <bsd.port.mk>
