# New ports collection makefile for:    font-bh-type1
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-bh-type1/Makefile,v 1.2 2010/05/01 11:40:54 miwi Exp $
#

PORTNAME=	font-bh-type1
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Bigelow Holmes Type1 font

XORG_CAT=	font

.include <bsd.port.mk>
