# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD$

PORTNAME=	libdevq
PORTVERSION=	0.1.0
CATEGORIES=	devel
MASTER_SITES=	http://rainbow-runner.nl/~kwm/distfiles/

MAINTAINER=	kwm@FreeBSD.org
COMMENT=	Generic Device Query and Monitor interface

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--disable-static
USE_XZ=		yes
USES=		pathfix
USE_LDCONFIG=	yes
INSTALL_TARGET=	install-strip

.include <bsd.port.mk>
