# New ports collection makefile for:	videoproto
# Date Created:				09 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/videoproto/Makefile,v 1.2 2010/05/01 11:40:17 miwi Exp $
#

PORTNAME=	videoproto
PORTVERSION=	2.3.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Video extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
