# New ports collection makefile for:	recordproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/recordproto/Makefile,v 1.2 2010/05/01 11:40:15 miwi Exp $
#

PORTNAME=	recordproto
PORTVERSION=	1.14
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	RECORD extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
