# New ports collection makefile for:    font-misc-misc
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-misc-misc/Makefile,v 1.2 2010/05/01 11:40:58 miwi Exp $
#

PORTNAME=	font-misc-misc
PORTVERSION=	1.1.0
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous Misc fonts

XORG_CAT=	font
USE_XORG=	fontutil

.include <bsd.port.mk>
