# New ports collection makefile for:	xf86-input-acecad
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-acecad/Makefile,v 1.10 2011/02/25 16:52:29 miwi Exp $
#

PORTNAME=	xf86-input-acecad
PORTVERSION=	1.5.0
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org acecad input driver

XORG_CAT=	driver
MAN4=		acecad.4x

.include <bsd.port.mk>
