# New ports collection makefile for:	xf86-input-acecad
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-acecad/Makefile,v 1.9 2010/05/07 03:37:43 miwi Exp $
#

PORTNAME=	xf86-input-acecad
PORTVERSION=	1.4.0
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org acecad input driver

XORG_CAT=	driver
MAN4=		acecad.4x

.include <bsd.port.mk>
