# New ports collection makefile for:	beforelight
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/beforelight/Makefile,v 1.2 2009/01/23 16:28:10 flz Exp $
#

PORTNAME=	beforelight
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	A sample screen saver for X

XORG_CAT=	app
USE_XORG=	x11 xscrnsaver xt xaw7 xt

MAN1=		beforelight.1

.include <bsd.port.mk>
