# $FreeBSD: head/x11-drivers/xf86-input-keyboard/Makefile 351936 2014-04-23 13:25:16Z tijl $

PORTNAME=	xf86-input-keyboard
PORTVERSION=	1.8.0
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org keyboard input driver

XORG_CAT=	driver
USE_XORG=	kbproto

.include <bsd.port.mk>
