# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXxf86vm/Makefile 351936 2014-04-23 13:25:16Z tijl $

PORTNAME=	libXxf86vm
PORTVERSION=	1.1.3
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Vidmode Extension

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	xproto x11 xextproto xext xf86vidmodeproto:both

.include <bsd.port.mk>
