# $FreeBSD: head/x11-drivers/xf86-video-fbdev/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	xf86-video-fbdev
PORTVERSION=	0.4.4
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org fbdev display driver

XORG_CAT=	driver

.include <bsd.port.mk>
