# New ports collection makefile for:	xf86-video-fbdev
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-fbdev/Makefile,v 1.6 2009/05/07 19:42:36 rnoland Exp $
#

PORTNAME=	xf86-video-fbdev
PORTVERSION=	0.4.1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org fbdev display driver

XORG_CAT=	driver
USE_XORG=	videoproto
MAN4=		fbdev.4x

.include <bsd.port.mk>
