# New ports collection makefile for:	xf86-video-fbdev
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-fbdev/Makefile,v 1.13 2012/04/21 17:03:24 miwi Exp $
#

PORTNAME=	xf86-video-fbdev
PORTVERSION=	0.4.3
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org fbdev display driver

XORG_CAT=	driver
MAN4=		fbdev.4x

.include <bsd.port.mk>
