# New ports collection makefile for:	xf86bigfontproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/xf86bigfontproto/Makefile,v 1.2 2010/05/01 11:41:02 miwi Exp $
#

PORTNAME=	xf86bigfontproto
PORTVERSION=	1.2.0
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XFree86-Bigfont extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
