# New ports collection makefile for:	damageproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/damageproto/Makefile,v 1.2 2010/05/01 11:40:07 miwi Exp $
#

PORTNAME=	damageproto
PORTVERSION=	1.2.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Damage extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
