# New ports collection makefile for:    font-arabic-misc
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-arabic-misc/Makefile,v 1.2 2010/05/01 11:40:51 miwi Exp $
#

PORTNAME=	font-arabic-misc
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous Arabic fonts

XORG_CAT=	font

.include <bsd.port.mk>
