# New ports collection makefile for:	iceauth
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/iceauth/Makefile,v 1.3 2010/05/01 11:40:09 miwi Exp $
#

PORTNAME=	iceauth
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	ICE authority file utility for X

XORG_CAT=	app
USE_XORG=	xproto ice

PLIST_FILES=	bin/iceauth

MAN1=		iceauth.1

.include <bsd.port.mk>
