# New ports collection makefile for:	xrefresh
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xrefresh/Makefile,v 1.2 2010/05/01 11:40:28 miwi Exp $
#

PORTNAME=	xrefresh
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Refresh all or part of an X screen

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xrefresh

MAN1=		xrefresh.1

.include <bsd.port.mk>
