# New ports collection makefile for:	bigreqsproto
# Date Created:				07 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/bigreqsproto/Makefile,v 1.1 2007/05/19 20:25:53 flz Exp $
#

PORTNAME=	bigreqsproto
PORTVERSION=	1.1.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	BigReqs extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
