# New ports collection makefile for:	xf86-input-penmount
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-penmount/Makefile,v 1.10 2010/05/07 03:37:44 miwi Exp $
#

PORTNAME=	xf86-input-penmount
PORTVERSION=	1.4.1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org penmount input driver

XORG_CAT=	driver
MAN4=		penmount.4x

.include <bsd.port.mk>
