# New ports collection makefile for:	evieext
# Date Created:				25 Apr 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/evieext/Makefile,v 1.2 2010/05/01 11:40:08 miwi Exp $
#

PORTNAME=	evieext
PORTVERSION=	1.1.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XEVIE extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
