# New ports collection makefile for:	xfindproxy
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xfindproxy/Makefile,v 1.1 2007/05/19 20:27:53 flz Exp $
#

PORTNAME=	xfindproxy
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Locate available proxy services

XORG_CAT=	app
USE_XORG=	x11 ice xt xproxymngproto

PLIST_FILES=	bin/xfindproxy

MAN1=		xfindproxy.1

.include <bsd.port.mk>
