# New ports collection makefile for:    font-sun-misc
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-sun-misc/Makefile,v 1.2 2010/05/01 11:40:59 miwi Exp $
#

PORTNAME=	font-sun-misc
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous Sun fonts

XORG_CAT=	font

.include <bsd.port.mk>
