# New ports collection makefile for:	mkcomposecache
# Date Created:				30 Jan 2007
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/mkcomposecache/Makefile,v 1.2 2010/05/01 11:40:15 miwi Exp $
#

PORTNAME=	mkcomposecache
PORTVERSION=	1.2.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Program to create Compose cache files

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	sbin/mkcomposecache

MAN8=		mkcomposecache.8

.include <bsd.port.mk>
