# New ports collection makefile for:	xf86-video-tseng
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-tseng/Makefile,v 1.9 2010/05/07 05:12:35 miwi Exp $
#

PORTNAME=	xf86-video-tseng
PORTVERSION=	1.2.3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org tseng display driver

XORG_CAT=	driver
USE_XORG=	videoproto xextproto
MAN4=		tseng.4x

.include <bsd.port.mk>
