# New ports collection makefile for:	xwud
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xwud/Makefile,v 1.2 2010/05/01 11:40:31 miwi Exp $
#

PORTNAME=	xwud
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Image displayer for X

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xwud

MAN1=		xwud.1

.include <bsd.port.mk>
