# New ports collection makefile for:    font-winitzki-cyrillic
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-winitzki-cyrillic/Makefile,v 1.2 2010/05/01 11:40:59 miwi Exp $
#

PORTNAME=	font-winitzki-cyrillic
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Winitzki Cyrillic font

XORG_CAT=	font

.include <bsd.port.mk>
