# New ports collection makefile for:	rstart
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/rstart/Makefile,v 1.1 2007/05/19 20:27:15 flz Exp $
#

PORTNAME=	rstart
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Sample implementation of a Remote Start client

XORG_CAT=	app
USE_XORG=	x11

MAN1=		rstart.1 rstartd.1

.include <bsd.port.mk>
