# New ports collection makefile for:	xf86bigfontproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/xf86miscproto/Makefile,v 1.2 2010/05/01 11:40:22 miwi Exp $
#

PORTNAME=	xf86miscproto
PORTVERSION=	0.9.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XFree86-Misc extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
