# New ports collection makefile for:	xsetroot
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xsetroot/Makefile,v 1.2 2007/09/13 19:45:06 flz Exp $
#

PORTNAME=	xsetroot
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	root window parameter setting utility for X

XORG_CAT=	app
USE_XORG=	xmuu x11 xbitmaps
MAN1=		xsetroot.1
PLIST_FILES=	bin/xsetroot

.include <bsd.port.mk>
