# New ports collection makefile for:	liboldX
# Date Created:				Dec 16 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/liboldX/Makefile,v 1.3 2009/08/02 19:36:09 mezz Exp $
#

PORTNAME=	liboldX
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Old X library

XORG_CAT=	lib
USE_XORG=	x11
USE_AUTOTOOLS=	libtool:22

.include <bsd.port.mk>
