# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libICE/Makefile 351936 2014-04-23 13:25:16Z tijl $

PORTNAME=	libICE
PORTVERSION=	1.0.9
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Inter Client Exchange library for X11

XORG_CAT=	lib
USE_XORG=	xproto:both xtrans

.include <bsd.port.mk>
