# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libICE/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	libICE
PORTVERSION=	1.0.8
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Inter Client Exchange library for X11

XORG_CAT=	lib
USE_XORG=	xproto:both xtrans

.include <bsd.port.mk>
