# New ports collection makefile for:   libICE
# Date Created:			09 Nov, 2003
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/libICE/Makefile,v 1.21 2010/05/01 11:40:09 miwi Exp $
#

PORTNAME=	libICE
PORTVERSION=	1.0.7
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Inter Client Exchange library for X11

XORG_CAT=	lib
USE_XORG=	xproto:both xtrans

.include <bsd.port.mk>
