# New ports collection makefile for:    font-bitstream-type1
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-bitstream-type1/Makefile,v 1.2 2010/05/01 11:40:55 miwi Exp $
#

PORTNAME=	font-bitstream-type1
PORTVERSION=	1.0.1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Bitstream Vera Type1 font

XORG_CAT=	font

.include <bsd.port.mk>
