# New ports collection makefile for:	xf86-video-s3virge
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-s3virge/Makefile,v 1.6 2009/05/07 19:42:38 rnoland Exp $
#

PORTNAME=	xf86-video-s3virge
PORTVERSION=	1.10.4
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org s3virge display driver

XORG_CAT=	driver
USE_XORG=	videoproto xextproto
MAN4=		s3virge.4x

.include <bsd.port.mk>
