# New ports collection makefile for:	xf86-video-rendition
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-rendition/Makefile,v 1.9 2010/05/07 05:12:34 miwi Exp $
#

PORTNAME=	xf86-video-rendition
PORTVERSION=	4.2.3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org rendition display driver

XORG_CAT=	driver
USE_XORG=	xextproto
MAN4=		rendition.4x

.include <bsd.port.mk>
