# New ports collection makefile for:	xf86-video-mach64
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-mach64/Makefile,v 1.8 2011/02/25 16:52:33 miwi Exp $
#

PORTNAME=	xf86-video-mach64
PORTVERSION=	6.9.0
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org mach64 display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	glproto videoproto xextproto xf86driproto xf86miscproto

.include <bsd.port.mk>
