# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXinerama/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	libXinerama
PORTVERSION=	1.1.3
PORTREVISION=	1
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 Xinerama library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto xineramaproto:both

.include <bsd.port.mk>
