# New ports collection makefile for:	xf86bigfontproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/xf86dgaproto/Makefile,v 1.2 2007/09/13 19:45:03 flz Exp $
#

PORTNAME=	xf86dgaproto
PORTVERSION=	2.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XFree86-DGA extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
