# New ports collection makefile for:	xditview
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xditview/Makefile,v 1.2 2009/01/23 16:28:17 flz Exp $
#

PORTNAME=	xditview
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Display ditroff output

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xditview.1

.include <bsd.port.mk>
