# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXau/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	libXau
PORTVERSION=	1.0.8
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Authentication Protocol library for X11

XORG_CAT=	lib
USE_XORG=	xproto:both

.include <bsd.port.mk>
