# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXau/Makefile 351936 2014-04-23 13:25:16Z tijl $

PORTNAME=	libXau
PORTVERSION=	1.0.8
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Authentication Protocol library for X11

XORG_CAT=	lib
USE_XORG=	xproto:both

.include <bsd.port.mk>
