# New ports collection makefile for:	xf86-video-nv
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-nv/Makefile,v 1.18 2009/05/07 19:42:37 rnoland Exp $
#

PORTNAME=	xf86-video-nv
PORTVERSION=	2.1.18
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org nv display driver

XORG_CAT=	driver
USE_XORG=	videoproto xextproto
MAN4=		nv.4x

.include <bsd.port.mk>
