# New ports collection makefile for:	xmessage
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xmessage/Makefile,v 1.4 2010/05/01 11:40:25 miwi Exp $
#

PORTNAME=	xmessage
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Display message or query in a X window

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xmessage.1

.include <bsd.port.mk>
