# New ports collection makefile for:	xf86-input-citron
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-citron/Makefile,v 1.10 2010/05/23 20:18:46 pav Exp $
#

PORTNAME=	xf86-input-citron
PORTVERSION=	2.2.2
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org citron input driver

XORG_CAT=	driver
MAN4=		citron.4x

.include <bsd.port.mk>
