# New ports collection makefile for:	xf86-video-voodoo
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-voodoo/Makefile,v 1.9 2010/05/07 05:12:36 miwi Exp $
#

PORTNAME=	xf86-video-voodoo
PORTVERSION=	1.2.3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org voodoo display driver

XORG_CAT=	driver
USE_XORG=	xf86dgaproto xextproto
MAN4=		voodoo.4x

.include <bsd.port.mk>
