# New ports collection makefile for:	xf86-input-hyperpen
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-hyperpen/Makefile,v 1.6 2010/02/07 15:25:23 rnoland Exp $
#

PORTNAME=	xf86-input-hyperpen
PORTVERSION=	1.3.0
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org hyperpen input driver

XORG_CAT=	driver

.include <bsd.port.mk>
