# New ports collection makefile for:	xbacklight
# Date Created:				11 Sep 2007
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xbacklight/Makefile,v 1.2 2010/05/01 11:40:18 miwi Exp $
#

PORTNAME=	xbacklight
PORTVERSION=	1.1.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Program to adjust backlight brightness

XORG_CAT=	app
USE_XORG=	x11 xrender xrandr

MAN1=		xbacklight.1
PLIST_FILES=	bin/xbacklight

.include <bsd.port.mk>
