# New ports collection makefile for:   libXdmcp
# Date Created:			28 Oct, 2003
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/libXdmcp/Makefile,v 1.15 2008/03/13 10:33:54 flz Exp $
#

PORTNAME=	libXdmcp
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Display Manager Control Protocol library

XORG_CAT=	lib
USE_XORG=	xproto:both

.include <bsd.port.mk>
