# New ports collection makefile for:    font-bitstream-speedo
# Date created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/font-bitstream-speedo/Makefile,v 1.1 2007/05/19 20:29:13 flz Exp $
#

PORTNAME=	font-bitstream-speedo
PORTVERSION=	1.0.0
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Bitstream Vera Speedo font

XORG_CAT=	font

.include <bsd.port.mk>
