# New ports collection makefile for:	xlsatoms
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xlsatoms/Makefile,v 1.2 2010/05/01 11:40:24 miwi Exp $
#

PORTNAME=	xlsatoms
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	List interned atoms defined on a server

XORG_CAT=	app
USE_XORG=	x11 xmuu

PLIST_FILES=	bin/xlsatoms

MAN1=		xlsatoms.1

.include <bsd.port.mk>
