# New ports collection makefile for:   libXt
# Date Created:			25 Jan, 2003
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11-toolkits/libXt/Makefile,v 1.24 2010/05/01 11:41:06 miwi Exp $
#

PORTNAME=	libXt
PORTVERSION=	1.0.9
CATEGORIES=	x11-toolkits

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Toolkit library

XORG_CAT=	lib
USE_XORG=	x11 sm xproto:both kbproto


.include <bsd.port.mk>
