# $FreeBSD$

PORTNAME=	xf86-input-mouse
PORTVERSION=	1.9.0
PORTREVISION=	1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org mouse input driver

XORG_CAT=	driver
USES=		pathfix
NO_STAGE=	yes

.include <bsd.port.mk>
