# $FreeBSD: head/x11-drivers/xf86-input-mouse/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	xf86-input-mouse
PORTVERSION=	1.9.0
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org mouse input driver

XORG_CAT=	driver
USES=		pathfix

.include <bsd.port.mk>
