# Created by: Florent Thoumie <flz@FreeBSD.org>
# $FreeBSD$

PORTNAME=	xf86-input-mouse
PORTVERSION=	1.8.1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org mouse input driver

XORG_CAT=	driver
USE_GNOME=	gnomehack
MAN4=		mousedrv.4x

.include <bsd.port.mk>
