# New ports collection makefile for:	xf86-input-fpit
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-fpit/Makefile,v 1.8 2010/05/23 20:21:12 pav Exp $
#

PORTNAME=	xf86-input-fpit
PORTVERSION=	1.3.0
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org fpit input driver

XORG_CAT=	driver
USE_XORG=	xrandr

MAN4=		fpit.4x

.include <bsd.port.mk>
