# New ports collection makefile for:	xf86rushproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/xf86rushproto/Makefile,v 1.1 2007/05/19 20:27:51 flz Exp $
#

PORTNAME=	xf86rushproto
PORTVERSION=	1.1.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XFree86-Rush extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
