# New ports collection makefile for:	xineramaproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/xineramaproto/Makefile,v 1.2 2010/05/01 11:40:23 miwi Exp $
#

PORTNAME=	xineramaproto
PORTVERSION=	1.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Xinerama extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
