# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXp/Makefile 351936 2014-04-23 13:25:16Z tijl $

PORTNAME=	libXp
PORTVERSION=	1.0.2
PORTREVISION=	2
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X print library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto xau printproto:both

.include <bsd.port.mk>
