# New ports collection makefile for:	libXfontcache
# Date Created:				21 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/libXfontcache/Makefile,v 1.1 2007/05/19 20:29:31 flz Exp $
#

PORTNAME=	libXfontcache
PORTVERSION=	1.0.5
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The Xfontcache library

XORG_CAT=	lib
USE_XORG=	fontcacheproto:both x11 xext xextproto

MAN3=		FontCacheChangeCacheSettings.3 \
		FontCacheQueryExtension.3 \
		FontCacheQueryVersion.3 \
		FontCacheGetCacheSettings.3 \
		FontCacheGetCacheStatistics.3 \
		Xfontcache.3

.include <bsd.port.mk>
