# New ports collection makefile for:	xload
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xload/Makefile,v 1.3 2009/01/23 16:28:20 flz Exp $
#

PORTNAME=	xload
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	System load average display for X

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xload.1

.include <bsd.port.mk>
