# New ports collection makefile for:	fontsproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/fontsproto/Makefile,v 1.2 2010/05/01 11:41:00 miwi Exp $
#

PORTNAME=	fontsproto
PORTVERSION=	2.1.0
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Fonts extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
