# New ports collection makefile for:	fontsproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/fontsproto/Makefile,v 1.1 2007/05/19 20:29:24 flz Exp $
#

PORTNAME=	fontsproto
PORTVERSION=	2.0.2
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Fonts extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
