# New ports collection makefile for:    font-cronyx-cyrillic
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-cronyx-cyrillic/Makefile,v 1.2 2010/05/01 11:40:55 miwi Exp $
#

PORTNAME=	font-cronyx-cyrillic
PORTVERSION=	1.0.1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Cronyx Cyrillic font

XORG_CAT=	font

.include <bsd.port.mk>
