# New ports collection makefile for:	xclipboard
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xclipboard/Makefile,v 1.2 2009/01/23 16:28:17 flz Exp $
#

PORTNAME=	xclipboard
PORTVERSION=	1.1.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X clipboard client

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xclipboard.1 xcutsel.1

.include <bsd.port.mk>
