# New ports collection makefile for:	x11perf
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/x11perf/Makefile,v 1.3 2010/05/01 11:40:18 miwi Exp $
#

PORTNAME=	x11perf
PORTVERSION=	1.5.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 server performance test program

XORG_CAT=	app
USE_XORG=	x11 xmuu xrender xft xext

MAN1=		Xmark.1 \
		x11perf.1 \
		x11perfcomp.1

.include <bsd.port.mk>
