# New ports collection makefile for:	xkbcomp
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xkbcomp/Makefile,v 1.2 2009/01/23 16:28:20 flz Exp $
#

PORTNAME=	xkbcomp
PORTVERSION=	1.1.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Compile XKB keyboard description

XORG_CAT=	app
USE_XORG=	x11 xkbfile

PLIST_FILES=	bin/xkbcomp

MAN1=		xkbcomp.1

.include <bsd.port.mk>
