# New ports collection makefile for:	font-util
# Date Created:				28 Aug 2005
# Whom:					Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-util/Makefile,v 1.2 2010/05/01 11:40:59 miwi Exp $
#

PORTNAME=	font-util
PORTVERSION=	1.2.0
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Create an index of X font files in a directory

XORG_CAT=	font

MAN1=		bdftruncate.1 ucs2any.1

.include <bsd.port.mk>
