# New ports collection makefile for:	xlogo
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xlogo/Makefile,v 1.3 2010/05/01 11:40:24 miwi Exp $
#

PORTNAME=	xlogo
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Displays the X Window System logo.

XORG_CAT=	app
USE_XORG=	xrender xft xext xt xaw xp xprintutil

MAN1=		xlogo.1

.include <bsd.port.mk>
