# New ports collection makefile for:	xf86-video-tga
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-tga/Makefile,v 1.13 2012/04/21 17:03:29 miwi Exp $
#

PORTNAME=	xf86-video-tga
PORTVERSION=	1.2.2
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org tga display driver

XORG_CAT=	driver
USE_XORG=	videoproto xextproto xf86dgaproto

.include <bsd.port.mk>
