# New ports collection makefile for:	smproxy
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/smproxy/Makefile,v 1.2 2010/05/01 11:40:17 miwi Exp $
#

PORTNAME=	smproxy
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Session Manager Proxy

XORG_CAT=	app
USE_XORG=	xt xmu

PLIST_FILES=	bin/smproxy

MAN1=		smproxy.1

.include <bsd.port.mk>
