# New ports collection makefile for:	xset
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xset/Makefile,v 1.4 2010/05/01 11:40:28 miwi Exp $
#

PORTNAME=	xset
PORTVERSION=	1.1.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	User preference utility for X

XORG_CAT=	app
USE_XORG=	xmuu

PLIST_FILES=	bin/xset

MAN1=		xset.1

.include <bsd.port.mk>
