# New ports collection makefile for:    font-xfree86-type1
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-xfree86-type1/Makefile,v 1.3 2010/05/01 11:41:00 miwi Exp $
#

PORTNAME=	font-xfree86-type1
PORTVERSION=	1.0.4
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org XFree86 Type1 font

XORG_CAT=	font

.include <bsd.port.mk>
