# New ports collection makefile for:	xkbevd
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xkbevd/Makefile,v 1.1 2007/05/19 20:27:56 flz Exp $
#

PORTNAME=	xkbevd
PORTVERSION=	1.1.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XKB event daemon

XORG_CAT=	app
USE_XORG=	xkbfile x11

PLIST_FILES=	bin/xkbevd

MAN1=		xkbevd.1

.include <bsd.port.mk>
