# New ports collection makefile for:	xstdcmap
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xstdcmap/Makefile,v 1.1 2007/05/19 20:28:16 flz Exp $
#

PORTNAME=	xstdcmap
PORTVERSION=	1.0.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X standard colormap utility

XORG_CAT=	app
USE_XORG=	xmu x11

PLIST_FILES=	bin/xstdcmap

MAN1=		xstdcmap.1

.include <bsd.port.mk>
