# New ports collection makefile for:    encodings
# Date created:				Oct 29 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/encodings/Makefile,v 1.2 2010/05/01 11:40:50 miwi Exp $
#

PORTNAME=	encodings
PORTVERSION=	1.0.4
PORTEPOCH=	1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Encoding fonts

XORG_CAT=	font
USE_XORG=	fontutil
FONTDIR=	encodings/large encodings

.include <bsd.port.mk>
