# New ports collection makefile for:    font-adobe-100dpi
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-adobe-100dpi/Makefile,v 1.1 2007/05/19 20:29:10 flz Exp $
#

PORTNAME=	font-adobe-100dpi
PORTVERSION=	1.0.0
PORTREVISION=	1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Adobe 100dpi font

XORG_CAT=	font
USE_XORG=	fontutil

.include <bsd.port.mk>
