# New ports collection makefile for:	xmag
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xmag/Makefile,v 1.3 2009/01/23 16:28:21 flz Exp $
#

PORTNAME=	xmag
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X application for screen magnifying

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xmag.1

.include <bsd.port.mk>
