# New ports collection makefile for:	xauth
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xauth/Makefile,v 1.3 2010/05/01 11:40:18 miwi Exp $
#

PORTNAME=	xauth
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X authority file utility

XORG_CAT=	app
USE_XORG=	x11 xau xext xmuu

PLIST_FILES=	bin/xauth

MAN1=		xauth.1

.include <bsd.port.mk>
