# New ports collection makefile for:    font-dec-misc
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-dec-misc/Makefile,v 1.1 2007/05/19 20:29:14 flz Exp $
#

PORTNAME=	font-dec-misc
PORTVERSION=	1.0.0
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous Dec fonts

XORG_CAT=	font

.include <bsd.port.mk>
