# New ports collection makefile for:   libXvMC
# Date Created:			8 Feb 206
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/libXvMC/Makefile,v 1.3 2010/05/01 11:40:13 miwi Exp $
#

PORTNAME=	libXvMC
PORTVERSION=	1.0.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Video Extension Motion Compensation library

XORG_CAT=	lib
USE_XORG=	x11 xext xv xextproto videoproto:both xproto:both

.include <bsd.port.mk>
