# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXvMC/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	libXvMC
PORTVERSION=	1.0.8
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Video Extension Motion Compensation library

XORG_CAT=	lib
USE_XORG=	x11 xext xv xextproto videoproto:both xproto:both

.include <bsd.port.mk>
