# New ports collection makefile for:	xgc
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xgc/Makefile,v 1.2 2009/01/23 16:28:19 flz Exp $
#

PORTNAME=	xgc
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X graphics demo

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xgc.1

.include <bsd.port.mk>
