# New ports collection makefile for:	xextproto
# Date Created:				07 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/xextproto/Makefile,v 1.4 2010/05/01 11:40:21 miwi Exp $
#

PORTNAME=	xextproto
PORTVERSION=	7.1.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XExt extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
