# New ports collection makefile for:	xmh
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xmh/Makefile,v 1.4 2009/01/23 16:28:22 flz Exp $
#

PORTNAME=	xmh
PORTVERSION=	1.0.1
PORTREVISION=	1
CATEGORIES=	x11 mail

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Send and read mail with an X interface to MH

RUN_DEPENDS+=	repl:${PORTSDIR}/mail/nmh

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xmh.1

.include <bsd.port.mk>
