# New ports collection makefile for:	listres
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD$
#

PORTNAME=	listres
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	List resources in widgets

XORG_CAT=	app
USE_XORG=	xproto xt xmu xaw

PLIST_FILES=	bin/listres

MAN1=		listres.1

.include <bsd.port.mk>
