# New ports collection makefile for:	listres
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/listres/Makefile,v 1.3 2010/05/01 11:40:15 miwi Exp $
#

PORTNAME=	listres
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	List resources in widgets

XORG_CAT=	app
USE_XORG=	x11 xt xmu xaw

PLIST_FILES=	bin/listres

MAN1=		listres.1

.include <bsd.port.mk>
