# New ports collection makefile for:    font-ibm-type1
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-ibm-type1/Makefile,v 1.2 2010/05/01 11:40:56 miwi Exp $
#

PORTNAME=	font-ibm-type1
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org IBM Type1 font

XORG_CAT=	font

.include <bsd.port.mk>
