# New ports collection makefile for:	xbiff
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xbiff/Makefile,v 1.3 2010/05/01 11:40:18 miwi Exp $
#

PORTNAME=	xbiff
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Mailbox flag for X

XORG_CAT=	app
USE_XORG=	xbitmaps xext xaw
MAN1=		xbiff.1
PLIST_FILES=	bin/xbiff

.include <bsd.port.mk>
