# New ports collection makefile for:	xf86-input-mutouch
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-mutouch/Makefile,v 1.10 2011/02/25 16:52:30 miwi Exp $
#

PORTNAME=	xf86-input-mutouch
PORTVERSION=	1.3.0
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org mutouch input driver

XORG_CAT=	driver
MAN4=		mutouch.4x

.include <bsd.port.mk>
