# New ports collection makefile for:   libXdamage
# Date Created:			13 Nov, 2003
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/libXdamage/Makefile,v 1.13 2007/05/19 20:26:49 flz Exp $
#

PORTNAME=	libXdamage
PORTVERSION=	1.1.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Damage extension library

XORG_CAT=	lib
USE_XORG=	x11 damageproto:both xfixes fixesproto xextproto xproto:both

.include <bsd.port.mk>
