# New ports collection makefile for:	xf86bigfontproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/xf86driproto/Makefile,v 1.3 2010/05/01 11:40:21 miwi Exp $
#

PORTNAME=	xf86driproto
PORTVERSION=	2.1.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XFree86-DRI extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
