# New ports collection makefile for:	xf86-input-elographics
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-elographics/Makefile,v 1.9 2011/02/25 16:52:29 miwi Exp $
#

PORTNAME=	xf86-input-elographics
PORTVERSION=	1.3.0
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org elographics input driver

XORG_CAT=	driver
MAN4=		elographics.4x

.include <bsd.port.mk>
