# New ports collection makefile for:	xf86-input-elographics
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-elographics/Makefile,v 1.8 2010/05/23 20:20:19 pav Exp $
#

PORTNAME=	xf86-input-elographics
PORTVERSION=	1.2.3
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org elographics input driver

XORG_CAT=	driver
MAN4=		elographics.4x

.include <bsd.port.mk>
