# New ports collection makefile for:	xcmiscproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/xcmiscproto/Makefile,v 1.2 2010/05/01 11:40:19 miwi Exp $
#

PORTNAME=	xcmiscproto
PORTVERSION=	1.2.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	XCMisc extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
