# New ports collection makefile for:	xmore
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xmore/Makefile,v 1.2 2009/01/23 16:28:22 flz Exp $
#

PORTNAME=	xmore
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Plain text display program for X

XORG_CAT=	app
USE_XORG=	xt xaw xp xprintutil

MAN1=		xmore.1

.include <bsd.port.mk>
