# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD$

PORTNAME=	inputproto
PORTVERSION=	2.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Input extension headers

USE_XORG=	xorg-macros
USE_PKGCONFIG=	build
XORG_CAT=	proto

CONFIGURE_ARGS=	--without-asciidoc

.include <bsd.port.mk>
