# New ports collection makefile for:	inputproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/inputproto/Makefile,v 1.6 2011/09/14 18:17:04 eadler Exp $
#

PORTNAME=	inputproto
PORTVERSION=	2.1.99.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Input extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
