# New ports collection makefile for:	mkfontdir
# Date Created:				28 Aug 2005
# Whom:					Pawel Worach
#
# $FreeBSD: ports/x11-fonts/mkfontdir/Makefile,v 1.4 2009/01/23 16:28:03 flz Exp $
#

PORTNAME=	mkfontdir
PORTVERSION=	1.0.5
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Create an index of X font files in a directory

RUN_DEPENDS=	mkfontscale:${PORTSDIR}/x11-fonts/mkfontscale

XORG_CAT=	app

PLIST_FILES=	bin/mkfontdir
MAN1=		mkfontdir.1

.include <bsd.port.mk>
