# New ports collection makefile for:    font-misc-cyrillic
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-misc-cyrillic/Makefile,v 1.2 2010/05/01 11:40:57 miwi Exp $
#

PORTNAME=	font-misc-cyrillic
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org miscellaneous Cyrillic font

XORG_CAT=	font

.include <bsd.port.mk>
