# New ports collection makefile for:	libfontenc
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/libfontenc/Makefile,v 1.1 2007/05/19 20:29:31 flz Exp $
#

PORTNAME=	libfontenc
PORTVERSION=	1.0.5
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The fontenc Library

XORG_CAT=	lib
USE_XORG=	xproto

.include <bsd.port.mk>
