# New ports collection makefile for:	libfontenc
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/libfontenc/Makefile,v 1.5 2011/11/09 15:26:03 miwi Exp $
#

PORTNAME=	libfontenc
PORTVERSION=	1.1.1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The fontenc Library

XORG_CAT=	lib
USE_XORG=	xproto

.include <bsd.port.mk>
