# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: head/x11-fonts/libfontenc/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	libfontenc
PORTVERSION=	1.1.2
PORTREVISION=	1
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The fontenc Library

XORG_CAT=	lib
USE_XORG=	xproto

.include <bsd.port.mk>
