# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXfixes/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	libXfixes
PORTVERSION=	5.0.1
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Fixes extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 fixesproto:both xproto:both xextproto

.include <bsd.port.mk>
