# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXfixes/Makefile 300897 2012-07-14 14:29:18Z beat $

PORTNAME=	libXfixes
PORTVERSION=	5.0
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Fixes extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 fixesproto:both xproto:both xextproto

MAN3=		Xfixes.3

.include <bsd.port.mk>
