# New ports collection makefile for:	xorg-docs
# Date Created:				Nov 2 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xorg-docs/Makefile,v 1.2 2007/09/13 19:45:05 flz Exp $
#

PORTNAME=	xorg-docs
PORTVERSION=	1.4
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.org documentation files

CONFLICTS=	XFree86-documents-* xorg-documents-*

XORG_CAT=	doc

.include <bsd.port.mk>
