# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: head/x11/xtrans/Makefile 351936 2014-04-23 13:25:16Z tijl $

PORTNAME=	xtrans
PORTVERSION=	1.3.4
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Abstract network code for X

LICENSE=	MIT

XORG_CAT=	lib

CONFIGURE_ARGS+=--disable-docs --without-xmlto

.include <bsd.port.mk>
