# Created by: Dejan Lesjak <lesi@FreeBSD.org>
# $FreeBSD: head/x11/xtrans/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	xtrans
PORTVERSION=	1.3.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Abstract network code for X

LICENSE=	MIT

XORG_CAT=	lib

CONFIGURE_ARGS+=--disable-docs --without-xmlto

.include <bsd.port.mk>
