# New ports collection makefile for:	xtrans
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/xtrans/Makefile,v 1.3 2009/01/23 16:28:25 flz Exp $
#

PORTNAME=	xtrans
PORTVERSION=	1.2.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Abstract network code for X

XORG_CAT=	lib

.include <bsd.port.mk>
