# New ports collection makefile for:	xgamma
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xgamma/Makefile,v 1.3 2010/05/01 11:40:22 miwi Exp $
#

PORTNAME=	xgamma
PORTVERSION=	1.0.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Gamma correction through the X server.

XORG_CAT=	app
USE_XORG=	x11 xxf86vm

PLIST_FILES=	bin/xgamma

MAN1=		xgamma.1

.include <bsd.port.mk>
