# New ports collection makefile for:	xf86-video-ark
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-ark/Makefile,v 1.6 2009/05/07 19:42:35 rnoland Exp $
#

PORTNAME=	xf86-video-ark
PORTVERSION=	0.7.2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org ark display driver

XORG_CAT=	driver
USE_XORG=	xextproto

.include <bsd.port.mk>
