# New ports collection makefile for:	glproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/glproto/Makefile,v 1.3 2009/05/28 22:19:38 rnoland Exp $
#

PORTNAME=	glproto
PORTVERSION=	1.4.12
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	GLX extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
