# New ports collection makefile for:	showfont
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/showfont/Makefile,v 1.3 2009/01/23 16:28:03 flz Exp $
#

PORTNAME=	showfont
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Font dumper for the X font server

XORG_CAT=	app
USE_XORG=	libfs

PLIST_FILES=	bin/showfont

MAN1=		showfont.1

.include <bsd.port.mk>
