# New ports collection makefile for:	xmodmap
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xmodmap/Makefile,v 1.3 2010/05/01 11:40:26 miwi Exp $
#

PORTNAME=	xmodmap
PORTVERSION=	1.0.4
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Utility for modifying keymaps and pointer button mappings in X

XORG_CAT=	app
USE_XORG=	x11

PLIST_FILES=	bin/xmodmap

MAN1=		xmodmap.1

.include <bsd.port.mk>
