# New ports collection makefile for:	compositeproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/compositeproto/Makefile,v 1.3 2010/05/01 11:40:07 miwi Exp $
#

PORTNAME=	compositeproto
PORTVERSION=	0.4.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Composite extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
