# New ports collection makefile for:	compositeproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/compositeproto/Makefile,v 1.2 2007/09/13 19:44:57 flz Exp $
#

PORTNAME=	compositeproto
PORTVERSION=	0.4.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Composite extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
