# New ports collection makefile for:	xf86-video-neomagic
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-neomagic/Makefile,v 1.9 2010/05/07 05:12:32 miwi Exp $
#

PORTNAME=	xf86-video-neomagic
PORTVERSION=	1.2.4
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org neomagic display driver

XORG_CAT=	driver
USE_XORG=	videoproto xextproto xf86dgaproto
MAN4=		neomagic.4x

.include <bsd.port.mk>
