# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXrandr/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	libXrandr
PORTVERSION=	1.4.2
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Resize and Rotate extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 randrproto:both xext xextproto xrender renderproto xproto:both

.include <bsd.port.mk>
