# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXrandr/Makefile 351936 2014-04-23 13:25:16Z tijl $

PORTNAME=	libXrandr
PORTVERSION=	1.4.2
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Resize and Rotate extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 randrproto:both xext xextproto xrender renderproto xproto:both

.include <bsd.port.mk>
