# New ports collection makefile for:	xf86-video-tdfx
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-tdfx/Makefile,v 1.13 2012/04/21 17:03:29 miwi Exp $
#

PORTNAME=	xf86-video-tdfx
PORTVERSION=	1.4.5
PORTREVISION=	2
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org tdfx display driver

USE_GL=		gl

XORG_CAT=	driver
USE_XORG=	xf86driproto videoproto xextproto glproto
MAN4=		tdfx.4x

.include <bsd.port.mk>
