# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libXxf86dga/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	libXxf86dga
PORTVERSION=	1.1.4
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X DGA Extension

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	xproto x11 xextproto xext xf86dgaproto:both

.include <bsd.port.mk>
