# New ports collection makefile for:	fontcacheproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/fontcacheproto/Makefile,v 1.1 2007/05/19 20:29:21 flz Exp $
#

PORTNAME=	fontcacheproto
PORTVERSION=	0.1.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Fontcache extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
