# New ports collection makefile for:	fontcacheproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/fontcacheproto/Makefile,v 1.2 2010/05/01 11:41:00 miwi Exp $
#

PORTNAME=	fontcacheproto
PORTVERSION=	0.1.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Fontcache extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
