# New ports collection makefile for:	xfontsel
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/xfontsel/Makefile,v 1.2 2009/01/23 16:28:03 flz Exp $
#

PORTNAME=	xfontsel
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Point and click selection of X11 font names

XORG_CAT=	app
USE_XORG=	xt xaw

MAN1=		xfontsel.1

.include <bsd.port.mk>
