# Created by: Florent Thoumie <flz@FreeBSD.org>
# $FreeBSD$

PORTNAME=	xf86-video-cirrus
PORTVERSION=	1.5.1
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org cirrus display driver

XORG_CAT=	driver
MAN4=		cirrus.4x

.include <bsd.port.mk>
