# New ports collection makefile for:	fixesproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/fixesproto/Makefile,v 1.1 2007/05/19 20:26:18 flz Exp $
#

PORTNAME=	fixesproto
PORTVERSION=	4.1.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Fixes extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
