# $FreeBSD$

PORTNAME=	libXScrnSaver
PORTVERSION=	1.2.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The XScrnSaver library

XORG_CAT=	lib
NO_STAGE=	yes
USE_XORG=	x11 xext xextproto scrnsaverproto:both

.include <bsd.port.mk>
