# $FreeBSD: head/x11/libXScrnSaver/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	libXScrnSaver
PORTVERSION=	1.2.2
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The XScrnSaver library

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto scrnsaverproto:both

.include <bsd.port.mk>
