# New ports collection makefile for:	libFS
# Date Created:				21 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/libFS/Makefile,v 1.7 2010/12/04 07:34:11 ade Exp $
#

PORTNAME=	libFS
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	The FS library

XORG_CAT=	lib
USE_XORG=	fontsproto:both xproto:both xtrans
USE_AUTOTOOLS=	libtool

.include <bsd.port.mk>
