# New ports collection makefile for:	randrproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/randrproto/Makefile,v 1.2 2009/04/04 04:03:55 rnoland Exp $
#

PORTNAME=	randrproto
PORTVERSION=	1.3.1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Randr extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
