# New ports collection makefile for:	randrproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/randrproto/Makefile,v 1.4 2011/02/25 16:52:15 miwi Exp $
#

PORTNAME=	randrproto
PORTVERSION=	1.4.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Randr extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
