# New ports collection makefile for:	xf86dga
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xf86dga/Makefile,v 1.2 2009/01/23 16:28:19 flz Exp $
#

PORTNAME=	xf86dga
PORTVERSION=	1.0.2
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Test program for the XFree86-DGA extension

XORG_CAT=	app
USE_XORG=	x11 xxf86dga xt xaw7 xmu

PLIST_FILES=	bin/dga

MAN1=		dga.1

.include <bsd.port.mk>
