# New ports collection makefile for:	xf86-input-void
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-input-void/Makefile,v 1.10 2011/02/25 16:52:31 miwi Exp $
#

PORTNAME=	xf86-input-void
PORTVERSION=	1.4.0
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org void input driver

XORG_CAT=	driver
MAN4=		void.4x

.include <bsd.port.mk>
