# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD: head/x11/libdmx/Makefile 351411 2014-04-16 18:28:47Z zeising $

PORTNAME=	libdmx
PORTVERSION=	1.1.3
PORTREVISION=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	DMX extension library

XORG_CAT=	lib
USE_XORG=	x11 xext xextproto dmxproto:both

.include <bsd.port.mk>
