# New ports collection makefile for:	xbitmaps
# Date Created:				17 Feb 2006
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/xbitmaps/Makefile,v 1.1 2007/05/19 20:27:37 flz Exp $
#

PORTNAME=	xbitmaps
PORTVERSION=	1.1.0
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org bitmaps data

CONFLICTS=	XFree86-libraries-* xorg-libraries-6.*

USE_GNOME=	gnomehack

XORG_CAT=	data

.include <bsd.port.mk>
