# New ports collection makefile for:	dmxproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/dmxproto/Makefile,v 1.2 2010/05/01 11:40:07 miwi Exp $
#

PORTNAME=	dmxproto
PORTVERSION=	2.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	DMX extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
