# New ports collection makefile for:	dmxproto
# Date Created:				06 Feb 2006
# Whom:					Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/dmxproto/Makefile,v 1.1 2007/05/19 20:26:01 flz Exp $
#

PORTNAME=	dmxproto
PORTVERSION=	2.3
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	DMX extension headers

XORG_CAT=	proto

.include <bsd.port.mk>
