# New ports collection makefile for:	xf86-video-r128
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11-drivers/xf86-video-r128/Makefile,v 1.11 2012/04/21 17:03:27 miwi Exp $
#

PORTNAME=	xf86-video-r128
PORTVERSION=	6.8.4
PORTREVISION=	3
CATEGORIES=	x11-drivers

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org r128 display driver

USE_GL=		gl
XORG_CAT=	driver
USE_XORG=	glproto xf86driproto xf86miscproto xineramaproto
MAN4=		r128.4x

.include <bsd.port.mk>
