# New ports collection makefile for:    font-alias
# Date created:		28 Aug 2005
# Whom:			Pawel Worach
#
# $FreeBSD: ports/x11-fonts/font-alias/Makefile,v 1.2 2010/05/01 11:40:51 miwi Exp $
#

PORTNAME=	font-alias
PORTVERSION=	1.0.3
CATEGORIES=	x11-fonts

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X.Org Font aliases

XORG_CAT=	font
FONTDIR=	100dpi 75dpi misc cyrillic

.include <bsd.port.mk>
