# New ports collection makefile for:   libXi
# Date Created:			22 Nov, 2003
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/libXi/Makefile,v 1.20 2010/05/01 11:40:12 miwi Exp $
#

PORTNAME=	libXi
PORTVERSION=	1.3.2
PORTEPOCH=	1
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Input extension library

XORG_CAT=	lib
USE_XORG=	xproto x11 xext xextproto inputproto:both

.include <bsd.port.mk>
