# New ports collection makefile for:   xrender
# Date Created:			2 Jul, 2003
# Whom:				Foxfair Hu <foxfair@FreeBSD.org>
#
# $FreeBSD: ports/x11/libXrender/Makefile,v 1.25 2010/05/01 11:40:12 miwi Exp $
#

PORTNAME=	libXrender
PORTVERSION=	0.9.5
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Render extension library

XORG_CAT=	lib
USE_XORG=	x11 renderproto:both xproto:both

.include <bsd.port.mk>
