# Created by: Foxfair Hu <foxfair@FreeBSD.org>
# $FreeBSD: head/x11/libXrender/Makefile 351936 2014-04-23 13:25:16Z tijl $

PORTNAME=	libXrender
PORTVERSION=	0.9.8
PORTREVISION=	2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X Render extension library

LICENSE=	MIT

XORG_CAT=	lib
USE_XORG=	x11 renderproto:both xproto:both

.include <bsd.port.mk>
