# New ports collection makefile for:	xvidtune
# Date Created:				17 Feb 2006
# Whom:					Florent Thoumie <flz@FreeBSD.org>
#
# $FreeBSD: ports/x11/xvidtune/Makefile,v 1.2 2009/01/23 16:28:25 flz Exp $
#

PORTNAME=	xvidtune
PORTVERSION=	1.0.2
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	Video mode tuner for X

XORG_CAT=	app
USE_XORG=	xxf86vm xt xaw

MAN1=		xvidtune.1

.include <bsd.port.mk>
