# Created by: Eric Anholt <anholt@FreeBSD.org>
# $FreeBSD$

PORTNAME=	xproto
PORTVERSION=	7.0.24
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 protocol headers

XORG_CAT=	proto
USE_XORG=	xorg-macros
USE_PKGCONFIG=	build

CONFIGURE_ARGS+=--disable-specs --without-fop --without-xmlto --without-xsltproc

.include <bsd.port.mk>
