# New ports collection makefile for:   xproto
# Date Created:			29 Oct, 2003
# Whom:				Eric Anholt <anholt@FreeBSD.org>
#
# $FreeBSD: ports/x11/xproto/Makefile,v 1.17 2010/05/01 11:40:27 miwi Exp $
#

PORTNAME=	xproto
PORTVERSION=	7.0.16
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	X11 protocol headers

XORG_CAT=	proto
USE_GNOME=	pkgconfig

.include <bsd.port.mk>
