# New ports collection makefile for:	renderproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/renderproto/Makefile,v 1.2 2007/09/13 19:45:01 flz Exp $
#

PORTNAME=	renderproto
PORTVERSION=	0.11
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	RenderProto protocol headers

XORG_CAT=	proto

.include <bsd.port.mk>
