# New ports collection makefile for:	renderproto
# Date Created:				08 Aug 2005
# Whom:					Dejan Lesjak <lesi@FreeBSD.org>
#
# $FreeBSD: ports/x11/renderproto/Makefile,v 1.3 2010/05/01 11:40:16 miwi Exp $
#

PORTNAME=	renderproto
PORTVERSION=	0.11
CATEGORIES=	x11

MAINTAINER=	x11@FreeBSD.org
COMMENT=	RenderProto protocol headers

XORG_CAT=	proto

.include <bsd.port.mk>
